package com.xiaoshabao.wechat.webservice.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-08T16:27:28.357+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "TokenServerWSImplService", 
                  wsdlLocation = "http://localhost:8080/shabao-test/ws/token?wsdl",
                  targetNamespace = "http://server.webservice.wechat.xiaoshabao.com/") 
public class TokenServerWSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.webservice.wechat.xiaoshabao.com/", "TokenServerWSImplService");
    public final static QName TokenServerWSImplPort = new QName("http://server.webservice.wechat.xiaoshabao.com/", "TokenServerWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/shabao-test/ws/token?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TokenServerWSImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/shabao-test/ws/token?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TokenServerWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TokenServerWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TokenServerWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public TokenServerWSImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TokenServerWSImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TokenServerWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns TokenServerWS
     */
    @WebEndpoint(name = "TokenServerWSImplPort")
    public TokenServerWS getTokenServerWSImplPort() {
        return super.getPort(TokenServerWSImplPort, TokenServerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TokenServerWS
     */
    @WebEndpoint(name = "TokenServerWSImplPort")
    public TokenServerWS getTokenServerWSImplPort(WebServiceFeature... features) {
        return super.getPort(TokenServerWSImplPort, TokenServerWS.class, features);
    }

}
