package com.xiaoshabao.wechat.webservice.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-08T16:27:28.298+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://server.webservice.wechat.xiaoshabao.com/", name = "TokenServerWS")
@XmlSeeAlso({ObjectFactory.class})
public interface TokenServerWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getToken", targetNamespace = "http://server.webservice.wechat.xiaoshabao.com/", className = "com.xiaoshabao.wechat.webservice.server.GetToken")
    @WebMethod
    @ResponseWrapper(localName = "getTokenResponse", targetNamespace = "http://server.webservice.wechat.xiaoshabao.com/", className = "com.xiaoshabao.wechat.webservice.server.GetTokenResponse")
    public com.xiaoshabao.wechat.webservice.server.AccessToken getToken(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );
}
